import = ["~/.config/alacritty/themes/themes/wombat.toml"]

[font]
size = 12.0

[font.normal]
family = "JetBrains Mono Nerd Font"

[font.offset]
x = 0
y = 0

[window]
padding = { x = 0, y = 0 }
decorations = "None"

[window.dimensions]
columns = 100
lines = 85
