theme = "catppuccin_latte"

[editor]
scrolloff = 6
middle-click-paste = false
scroll-lines = 2
line-number = "relative"
bufferline = "multiple"
text-width = 50

[editor.gutters]
layout = ["spacer", "line-numbers", "spacer"]

[editor.soft-wrap]
enable = true

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
